### ISSUE TITLE
Publishing scoped packages

### ISSUE THREAD

**Issue by IdanAdar** [JS-DevTools/npm-publish#22]
I have a scoped package that is meant to be public, this should be accomplished with “—access public”, but the doc makes it sound like scoped packages should not use this, which is confusing...

**Comment by noah-friedman** [comment]
I'm confused about this as well. There doesn't seem to be a way to publish scoped packages with this action.

**Comment by JamesMessinger** [comment]
This module works the same as the NPM CLI.  Just like the NPM CLI, the `access` option defaults to `public` for non-scoped packages and `restricted` for scoped packages.  So, if you want to publish a scoped package that is accessible by anyone, then set the `access` option to `public`.
