### ISSUE TITLE
Add an option to only allow incremental package versions to be published

### ISSUE THREAD

**Issue by Tohaker** [JS-DevTools/npm-publish#43]
It appears that using the `semver.diff` function only checks if the package version is different, and subsequently ignores whether the version is actually a higher or lower version.

I'd like to add an option that uses `semver.compare` to only run if the new package version is higher than that already published. I'm thinking something along the lines of `greater-version` (default: `false`, for backwards compatibility).

I'll raise a PR with an implementation too.

**Comment by mcous** [comment]
Resolved by #44 and #58. Not yet released to a tag, but in the mean time should be available via the commit directly: `8a7309043b3e67e38892ed629a136899c3cf166a`
