### ISSUE TITLE
Any way to don't publish if not already published?

### ISSUE THREAD

**Issue by SrBrahma** [JS-DevTools/npm-publish#48]
Hi! I've been using it for a while and I appreciate your work ;)

I want to include it on my boilerplates generator, but I would like that it would only run publish if the package is already published, to avoid accidental publishing due to some specific reasons. I know right that it's possible to use another branch to avoid the publishing, but I want to know if it's possible.

Thanks!

**Comment by Vanthang1995** [comment]
![Uploading Screenshot_20220205-200934_B29.jpg…]()

**Comment by Vanthang1995** [comment]
11

**Comment by mcous** [comment]
Thanks for the request! I don't think it's worth adding this feature to this action. If you would like to prevent a package from being published until it's ready, you should set `"private": true` in `package.json`
