### ISSUE TITLE
Configure publish directory

### ISSUE THREAD

**Issue by ekabolotina** [JS-DevTools/npm-publish#59]
The signature of `npm publish` command allows to define the folder used as root: 
```bash
npm publish [<tarball>|<folder>] [--tag <tag>] [--access <public|restricted>] [--dry-run]
```
Is it possible to configure `<folder>` parameter when using `JS-DevTools/npm-publish` action?

**Comment by razor-x** [comment]
Should be handled with the proposal in this issue: https://github.com/JS-DevTools/npm-publish/issues/81
