### ISSUE TITLE
Upgrade Action to use node 16 instead of node 12

### ISSUE THREAD

**Issue by ericcornelissen** [JS-DevTools/npm-publish#61]
Following the recent blog post ["GitHub Actions: All Actions will begin running on Node16 instead of Node12"](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) by GitHub, I noticed this action is still running on `node12`:

https://github.com/JS-DevTools/npm-publish/blob/e42e3720bfe21259120218c19fdbfedcf72692bd/action.yml#L58-L60

It should be fairly easy to change this by replacing `using: node12` with `using: node16` - I wouldn't expect anything in this Action's source code to break as a result of that.

One thing to note, by and large I've seen other Actions use a major version bump when releasing this change. The motivation being that older GitHub Actions runners may not support `node16`. See for example the ["What's new" section of `actions/checkout`](https://github.com/actions/checkout/tree/e6d535c99c374d0c3f6d8cd8086a57b43c6c700a#whats-new).

**Comment by razor-x** [comment]
I've opened a PR with this update: https://github.com/JS-DevTools/npm-publish/pull/68
