### ISSUE TITLE
Question about npm publishing with 2FA on

### ISSUE THREAD

**Issue by oatymart** [JS-DevTools/npm-publish#7]
Hi,
before trying, I would like to know if it's possible to use this action when you have 2FA configured on your npm account?
When I publish manually using `npm publish`, I'm prompted for my OTP. Will this prevent the action from completing?

**Comment by JamesMessinger** [comment]
I have 2FA enabled for my NPM account, and this action works great for me.  But I think you can _also_ enable a stricter form of 2FA in NPM, where the OTP has to be re-entered every time you publish a package, and I'm not sure whether this action will work in that case.

**Comment by oatymart** [comment]
Sadly under my npm organisation's current publishing settings, this action fails with:
```
npm ERR! code EOTP
npm ERR! This operation requires a one-time password from your authenticator.
npm ERR! You can provide a one-time password by passing --otp=<code> to the command you ran.
npm ERR! If you already provided a one-time password then it is likely that you either typoed
npm ERR! it, or it timed out. Please try again.
```
Since there doesn't seem to be any workaround offered by npm, having 2FA-for-publishing and publishing via an action seems to be, as expected, a no-go.

**Comment by yordis** [comment]
I think this should be close,

NPM has a token type for integrations such as CI/CD that will bypass 2MFA.

![Screen Shot 2021-09-16 at 12 00 48 AM](https://user-images.githubusercontent.com/4237280/133547460-20788b3e-921c-4a20-8701-c78eec5884db.png)
