### ISSUE TITLE
Chore: release version 2

### ISSUE THREAD

**Issue by mcous** [JS-DevTools/npm-publish#74]
We need to release a new version of this action! Planned changes:

- [x] Fix: switch to Node v16 due to deprecation of Node v14 actions
    - #61
- [x] Fix: upgrade `@actions/core` due to deprecation of stdout-based output variables
    - #67
- [x] Fix: do **not** mess with `~/.npmrc`
    - #15
- [x] Feature: add ability to pass `package_spec` to `npm publish`
    - #59 
- [x] Feature: add ability to pass a `.tgz` to `npm publish`
    - #81
- [x] Fix (**BREAKING**): Re-work call to npm to avoid changing the working directory
    - #51
- [x] Fix (**BREAKING**): pass `--ignore-scripts` to npm by default
    - #47
- [x] Chore (**BREAKING**): Drop support for Node v14 and below in npm package due to imminent v14 EOL

There's a few other bug issues open, but nothing that looks like a breaking change. If we can land fixes, great, but getting the deprecations fixed is the priority given the June 1 deadline.

Release should happen on a Monday, Tuesday, or Wednesday to give any users of this action (and us!) time during the week to react to any issues.

**Comment by razor-x** [comment]
This one can probably go on the list: https://github.com/JS-DevTools/npm-publish/issues/81
