### ISSUE TITLE
Question: `rc` version release

### ISSUE THREAD

**Issue by danpacho** [JS-DevTools/npm-publish#87]
What if publishing package with this action for `rc` version, like `version: "1.0.0-rc.0"`?

Expected behavior is that `npm publish --tag rc` script is automatically adapted, because `rc` tag is included in version string.

And after automatically publishing process via this action, package can then be installed with the following command
`npm install my-package@rc`

**Comment by mcous** [comment]
I would prefer this module to be a pretty thin wrapper around vanilla npm behavior, so I'm not interesting in doing anything clever with parsing the version string at this time.

This action will fall back to the [`publishConfig` field](https://docs.npmjs.com/cli/v9/configuring-npm/package-json?v=true#publishconfig) in `package.json`, so if you're interested in using this action to publish pre-release versions in some automated fashion, I recommend you use that functionality:

For example:

```json
{
  "name": "my-cool-package",
  "version": "1.0.0-rc.0",
  "publishConfig": {
    "tag": "rc"
  }
}
```

**Comment by danpacho** [comment]
Thanks! 🙂
